/* ============================================================
   TLNT.AE Resume Formatter - shared engine
   Used by index.html (editor) and view.html (shared link view)
   ============================================================ */
(function(global){
"use strict";

if (global.pdfjsLib) pdfjsLib.GlobalWorkerOptions.workerSrc =
  "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js";

const FONTS = {
  reg:  "https://cdn.jsdelivr.net/npm/@expo-google-fonts/roboto@0.2.3/Roboto_400Regular.ttf",
  med:  "https://cdn.jsdelivr.net/npm/@expo-google-fonts/roboto@0.2.3/Roboto_500Medium.ttf",
  bold: "https://cdn.jsdelivr.net/npm/@expo-google-fonts/roboto@0.2.3/Roboto_700Bold.ttf",
};
let fontCache = null;

/* ---- sources / watermarks to strip ---- */
const SOURCE_WORDS = [
 "linkedin","indeed","glassdoor","monster.com","ziprecruiter","careerbuilder","simplyhired",
 "snagajob","flexjobs","dice.com","cv-library","totaljobs","reed.co.uk","seek.com",
 "hh.ru","headhunter","superjob","rabota.ru","zarplata","habr career","geekjobs",
 "work.ua","rabota.ua","jooble","talent.com","adzuna","neuvoo","jobs.ge",
 "naukri","bayt.com","gulftalent","laimoon","dubizzle","jobstreet","glints","foundit","shine.com","timesjobs",
 "contactout","rocketreach","lusha","apollo.io","signalhire","hunter.io","kaspr","cognism",
 "upwork","fiverr","freelancer.com","angellist","wellfound","xing.com",
 "resume.io","resume-now","novoresume","zety","enhancv","myperfectresume","kickresume","flowcv","visualcv",
 "indeed.com","glassdoor.com"
];
// resume builders that stamp their name on exports ("Made with Canva", "Powered by Zety")
const TOOL_WORDS = ["canva","zety","enhancv","novoresume","kickresume","resume.io","resume-now","flowcv","visualcv",
 "myperfectresume","livecareer","resume genius","resumegenius","cvmaker","cv maker","europass","resumonk","rezi","jobscan",
 "resume builder","cv builder","конструктор резюме"];
const reEsc=s=>s.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
const SRC_ALT=SOURCE_WORDS.map(reEsc).join("|"), STAMP_ALT=SOURCE_WORDS.concat(TOOL_WORDS).map(reEsc).join("|");
const SRC_RE=new RegExp("(?<![\\p{L}\\p{N}])(?:"+SRC_ALT+")(?![\\p{L}\\p{N}])","iu");
const SRC_RE_G=new RegExp(SRC_RE.source,"giu");
const STAMP_RE=new RegExp("(?<![\\p{L}\\p{N}])(?:"+STAMP_ALT+")(?![\\p{L}\\p{N}])","iu");
const WM_DOMAIN_RE=/(?:https?:\/\/|www\.)\S+|(?<![\p{L}\p{N}@])[a-z0-9-]+(?:\.[a-z0-9-]+)*\.(?:com|ru|io|net|org|ae|co|me|in|ua|kz|de|uk|ge|by|uz)(?![\p{L}\p{N}])/iu;
const WM_DATE_RE=/\d{1,2}[./-]\d{1,2}[./-]\d{2,4}|\d{4}-\d{2}-\d{2}|(?<!\d)(?:19|20)\d{2}(?!\d)/;
// Only a WHOLE short line that is a stamp is dropped. A sentence that merely starts with "Created", "Built with" or
// mentions a job board stays: "Created onboarding program...", "Built with the CTO...", "Senior Headhunter".
function isWatermarkLine(raw){
  const t=String(raw||"").trim().replace(/\s+/g," ");
  if(!t || t.length>90) return false;
  // page counters: "Page 1 of 2", "2 / 3", "Стр. 1 из 2"
  if(/^(?:page\s+)?\d{1,3}\s*(?:of|\/|из)\s*\d{1,3}$/i.test(t) || /^стр(?:аница)?\.?\s*\d{1,3}(?:\s*(?:из|\/)\s*\d{1,3})?$/i.test(t)) return true;
  // a profile counter standing alone: "500+ connections", "1 200 followers", "350 контактов"
  if(/^\d[\d\s.,]*\+?\s*(?:connections?|followers?|подписчик\p{L}*|контакт\p{L}*)$/iu.test(t)) return true;
  // "Powered by Zety", "Made with Canva", "Generated on 12.03.2024", "Downloaded from LinkedIn", "This CV was generated by..."
  const m=t.match(/^(this\s+(?:resume|cv)\s+(?:was|is)\s+|(?:resume|cv)\s+)?(powered|generated|created|made|built|downloaded|exported|imported|printed)\s+(?:by|with|on|from|using|via|in|at)\s+(.+)$/i);
  if(m){
    const verb=m[2].toLowerCase(), tail=m[3];
    if(m[1] && /^this/i.test(m[1])) return true;
    if(verb==="powered" && tail.split(" ").length<=5) return true;
    if(STAMP_RE.test(tail) || WM_DOMAIN_RE.test(tail)) return true;
    if(/^(generated|downloaded|exported|imported|printed)$/.test(verb) && WM_DATE_RE.test(tail) && tail.split(" ").length<=6) return true;
  }
  // "Source: hh.ru", "Public profile: linkedin.com/in/...", "View profile on LinkedIn", "Profile URL: ..."
  if(/^(?:source|источник)\s*:/i.test(t) && t.length<=70) return true;
  if(/^(?:public\s+profile|view\s+(?:my\s+)?(?:full\s+)?profile|profile\s+url)(?![\p{L}])/iu.test(t)) return true;
  // hh.ru and other Russian boards: "Резюме обновлено 1 октября 2026 в 10:00", "Резюме с сайта hh.ru", "Сформировано на hh.ru 12.03.2024"
  if(/^(?:резюме\s+)?обновлен\p{L}*\s+\d/iu.test(t)) return true;
  if(t.length<=80 && /^резюме\s+(?:обновлено|создано|подготовлено|сформировано|скачано|сгенерировано|выгружено|загружено)(?![\p{L}])/iu.test(t)) return true;
  if(/^резюме\s+(?:с|на)\s+сайт/iu.test(t)) return true;
  const r=t.match(/^(сформировано|сгенерировано|скачано|выгружено|загружено|экспортировано|создано|подготовлено|получено)(?:\s+(?:с\s+помощью|на|с|в|из|через))?\s+(.+)$/iu);
  if(r){
    const verb=r[1].toLowerCase(), tail=r[2];
    if(STAMP_RE.test(tail) || WM_DOMAIN_RE.test(tail) || /^(?:сайт|сервис|конструктор|платформ)/iu.test(tail)) return true;
    if(!/^(создано|подготовлено|получено)$/.test(verb) && WM_DATE_RE.test(tail) && tail.split(" ").length<=6) return true;
  }
  return false;
}
// a stamp glued to the end of a real sentence: "...12 лет. Резюме обновлено 1 октября 2026", "... Powered by Zety"
const STAMP_TAIL_RE=new RegExp("(?:^|(?<=[\\s.,;|]))\\s*(?:(?:резюме\\s+)?обновлено\\s+\\d{1,2}\\s+\\p{L}+\\s+\\d{4}(?:\\s+в\\s+\\d{1,2}:\\d{2})?|powered\\s+by\\s+(?:"+STAMP_ALT+")(?:\\s+[\\p{L}.]+){0,3}|(?:made|created|generated|built)\\s+(?:with|by|in|using)\\s+(?:"+STAMP_ALT+")(?:\\s+[\\p{L}.]+){0,2})\\s*\\.?$","iu");
// "... downloaded from LinkedIn", "... via hh.ru", "(source: Indeed)", "Сформировано на HeadHunter" at the END of a line
const SRC_TAIL_RE=new RegExp("[\\s,;:|(\\p{Pd}]*(?:(?:downloaded|exported|imported|sourced|found|taken|copied|parsed|scraped|received|retrieved)\\s+(?:from|via|on|at)|(?<![\\p{L}])via|(?:сформировано|скачано|загружено|взято|выгружено|получено|найдено)\\s+(?:на|с|из|в|через)|(?:source|источник)\\s*:)\\s*(?:the\\s+)?(?:сайта\\s+)?(?:"+SRC_ALT+")(?:\\s+(?:profile|resume|cv|website|site|platform|профиль|резюме))?[\\s.)]*$","iu");

/* section header dictionary -> normalized label */
const HEAD_MAP = [
 [/^(summary|profile|about( me)?|objective|overview|professional summary)(?![a-zа-яё])/i,"Summary"],
 [/^(о себе|обо мне|профиль|краткая информация)(?![a-zа-яё])/i,"О себе"],
 [/^(желаемая должность.*|желаемая зарплата)/i,"Желаемая должность"],
 [/^(experience|work experience|employment( history)?|work history|professional experience|career)(?![a-zа-яё])/i,"Experience"],
 [/^(опыт работы|места работы|трудовой опыт)(?![a-zа-яё])/i,"Опыт работы"],
 [/^(education|academic background|qualifications)(?![a-zа-яё])/i,"Education"],
 [/^(высшее образование|неоконченное высшее|среднее специальное|образование|обучение)(?![a-zа-яё])/i,"Образование"],
 [/^(skills|technical skills|core skills|hard skills|soft skills|key skills|competenc(e|ies)|top skills|core competenc(e|ies)|key competenc(e|ies)|areas? of expertise|technical expertise|professional skills|personal skills|additional skills)(?![a-zа-яё])/i,"Skills"],
 [/^(ключевые навыки|навыки|компетенции|технические навыки|профессиональные навыки|основные навыки)(?![a-zа-яё])/i,"Навыки"],
 [/^(research experience|teaching experience|relevant experience|leadership experience)(?![a-zа-яё])/i,"Experience"],
 [/^(research interests?)(?![a-zа-яё])/i,"Research Interests"],
 [/^(professional development)(?![a-zа-яё])/i,"Professional Development"],
 [/^(personal information|personal details|contact information|contact details|personal data)(?![a-zа-яё])/i,"__PERSONAL__"],
 [/^(projects?|portfolio)(?![a-zа-яё])/i,"Projects"],
 [/^(проекты)(?![a-zа-яё])/i,"Проекты"],
 [/^(certification?s?|certificates?|courses?|training)(?![a-zа-яё])/i,"Certifications"],
 [/^(сертификаты|курсы|повышение квалификации.*)(?![a-zа-яё])/i,"Курсы"],
 [/^(languages?)(?![a-zа-яё])/i,"Languages"],
 [/^(знание языков|владение языками|языки)(?![a-zа-яё])/i,"Языки"],
 [/^(achievements?|awards?|honors?)(?![a-zа-яё])/i,"Achievements"],
 [/^(достижения|награды)(?![a-zа-яё])/i,"Достижения"],
 [/^(interests?|hobbies)(?![a-zа-яё])/i,"Interests"],
 [/^(интересы|хобби|увлечения)(?![a-zа-яё])/i,"Интересы"],
 [/^(publications?)(?![a-zа-яё])/i,"Publications"],
 [/^(references?)(?![a-zа-яё])/i,"References"],
 [/^(рекомендации)(?![a-zа-яё])/i,"Рекомендации"],
 [/^(дополнительная информация)(?![a-zа-яё])/i,"Дополнительно"],
 [/^(контакты|контактная информация|контактные данные|способы связаться|способы связи|связаться со мной)(?![a-zа-яё])/i,"__CONTACTS__"],
 [/^(contacts?|contact (information|details)|how to (reach|contact)|ways to (reach|contact))(?![a-zа-яё])/i,"__CONTACTS__"],
];

const EMAIL_RE = /[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,}/i;
const EMAIL_G_RE = new RegExp(EMAIL_RE.source,"gi");
const PHONE_RE = /(\+?\(?\d[\d\s().\-]{7,}\d)/;

/* ---- phone picking: the first digit run is often a period or an ID, not the phone ---- */
const PHONE_LINE_RE = /\+?\(?\d(?:[\d().\-]|[^\S\r\n]){7,}\d/g;   // never crosses a line break ("915264444\n2023")
const PHONE_LABEL_RE = /(?<![\p{L}])(phone|telephone|tel|mobile|mob|cell|whatsapp|телефон|тел|мобильный|моб|сотовый)(?![\p{L}])/iu;
const ID_LABEL_RE = /((?<![\p{L}])(id|no|passport|contract|policy|invoice|account|iban|license|licence|паспорт|договор|полис|инн|снилс)|№|n°|#)\s*[.:]?\s*$/iu;
const isYear = g => /^(19|20)\d{2}$/.test(g);
// digits that are not a phone: too short ("36.6"), a period ("2018 - 2024", "2013 2003"), a date ("11.06.1984", "01.2019 - 05.2021")
function phoneJunk(p){
  const g=p.match(/\d+/g)||[];
  if(g.join("").length<7) return true;
  if(g.every(isYear)) return true;
  if(g.some(isYear) && g.every(x=>x.length<=2||isYear(x))) return true;
  return false;
}
// first plausible phone in the text; "+", a phone label or grouped digits win over a bare number sitting inside other text
function findPhone(text){
  let fallback="";
  for(const line of String(text||"").split("\n")){
    for(const m of line.matchAll(PHONE_LINE_RE)){
      let p=m[0].trim();
      if(p[0]==="(" && !p.includes(")")) p=p.slice(1);          // "(2018 - 2020"
      const before=line.slice(0,m.index), after=line.slice(m.index+m[0].length);
      if(phoneJunk(p)) continue;
      if(p[0]!=="+" && /\p{L}$/u.test(before)) continue;          // tail of a code: "CMX094025509", "ivan1234567@..."
      const labeled=PHONE_LABEL_RE.test(line);
      if(p[0]!=="+" && !PHONE_LABEL_RE.test(before) && ID_LABEL_RE.test(before)) continue;   // "Contract n°: 915264444"
      if(/^\s*(₽|руб|\$|€|aed|usd|eur|rub|тыс)/iu.test(after)) continue;                       // salary, not a phone
      const grouped=/^\(\d{2,5}\)/.test(p) || (p.match(/\d+/g)||[]).length>=3;
      const chunk=before.split(/[|•·;,]/).pop();                   // "Dubai, UAE | 0501234567" is a contact row, not text
      const inText=/\p{L}/u.test(chunk.replace(EMAIL_RE,"").replace(/https?:\/\/\S+|www\.\S+/gi,""));
      if(p[0]==="+" || labeled || grouped || !inText) return p;
      if(!fallback) fallback=p;
    }
  }
  return fallback;
}
const URL_RE   = /\b((https?:\/\/)?(www\.)?[a-z0-9\-]+\.[a-z]{2,}(\/[^\s]*)?)\b/i;
const PERSONAL_RE = /(мужчина|женщина|\d+\s+(год|года|лет)|родил|проживает|гражданств|разрешение на работу|готов(а)? к переезд|готов(а)? к командиров|не готов|тип занятости|формат работы|время в пути|желательное время|занятость|желаемая зарплата|date of birth|nationality|marital status)/i;

const JOB_TITLE_RE = /\b(director|manager|engineer|developer|designer|analyst|consultant|specialist|officer|lead|head\s+of|chief|cxo|cto|cfo|ceo|coo|president|founder|co-?founder|nurse|accountant|architect|administrator|coordinator|executive|supervisor|technician|teacher|professor|scientist|marketer|recruiter|strategist|owner|partner|associate|intern|руководитель|директор|менеджер|инженер|разработчик|дизайнер|аналитик|специалист|бухгалтер|консультант|маркетолог|администратор|руководител)\b/i;

/* ---- location detection (generic, not a fixed city list) ---- */
const COUNTRY_RE=/(?<![\p{L}])(uae|united arab emirates|emirates|usa|u\.s\.a\.|united states|uk|united kingdom|england|scotland|ireland|canada|germany|deutschland|france|italy|italia|spain|españa|portugal|poland|polska|netherlands|belgium|sweden|norway|denmark|finland|switzerland|austria|greece|turkey|türkiye|egypt|saudi arabia|saudi|qatar|kuwait|bahrain|oman|jordan|lebanon|morocco|nigeria|kenya|ghana|south africa|japan|china|hong kong|singapore|malaysia|indonesia|thailand|vietnam|philippines|india|pakistan|bangladesh|australia|new zealand|brazil|brasil|argentina|chile|colombia|mexico|méxico|россия|russia|казахстан|kazakhstan|украина|ukraine|беларусь|belarus|узбекистан|армения|грузия|georgia|azerbaijan|азербайджан|оаэ|эмираты|катар|саудовская аравия|кувейт|бахрейн|оман|египет|турция|германия|франция|испания|италия|польша|нидерланды|швейцария|сербия)(?![\p{L}])/iu;
const US_STATE_RE=/,\s*(AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC)\b/;
const CITY_RE=/(?<![\p{L}])(dubai|abu dhabi|sharjah|ajman|doha|riyadh|jeddah|kuwait city|manama|muscat|дубай|абу[\s-]?даби|шарджа|аджман|доха|эр[\s-]?рияд|джидда|манама|маскат|london|manchester|new york|san francisco|los angeles|chicago|boston|seattle|austin|houston|dallas|miami|toronto|vancouver|berlin|munich|hamburg|paris|madrid|barcelona|rome|milan|amsterdam|brussels|zurich|geneva|vienna|warsaw|prague|stockholm|oslo|copenhagen|helsinki|istanbul|cairo|lagos|nairobi|cape town|johannesburg|tokyo|osaka|beijing|shanghai|hong kong|singapore|kuala lumpur|bangkok|jakarta|mumbai|delhi|bangalore|bengaluru|hyderabad|sydney|melbourne|sao paulo|são paulo|mexico city|москва|moscow|санкт\s*-?\s*петербург|петербург|st\.? petersburg|екатеринбург|новосибирск|казань|нижний новгород|самара|краснодар|алматы|астана|almaty|astana|tashkent|ташкент|baku|баку|tbilisi|тбилиси|минск|minsk|kyiv|kiev|киев)(?![\p{L}])/iu;
const LOC_PREFIX_RE=/^\s*(location|address|based in|city|town|город(?:\s+проживания)?|адрес|местоположение|проживает|residence)\s*[:\-\u2013]\s*/i;
function looksLikeLocationChunk(s){
  s=(s||"").trim();
  if(!s||s.length>44||s.split(/\s+/).length>6) return false;
  if(EMAIL_RE.test(s)||/[@]|https?:|www\.|\.com|\.ru|\d{4,}/i.test(s)) return false;   // no years/IDs
  if(/гражданств|разрешение|nationality|date of birth|родил|university|универ|институт|college|школа|degree|ph\.?\s?d|phd|doctorate|diploma|b\.?sc|m\.?sc|mba|bachelor|master|факультет|кафедр/i.test(s)) return false;
  if(LOC_PREFIX_RE.test(s)) return true;
  if(US_STATE_RE.test(s)) return true;
  if(COUNTRY_RE.test(s)) return true;
  if(CITY_RE.test(s)) return true;
  if(/\b(bay area|greater\s+\w+\s+area|metropolitan area|\w+\s+region)\b/i.test(s)) return true;
  return false;
}
function tidyLoc(s){
  return (s||"")
    .replace(/([а-яёa-z])\s*-\s*([а-яёa-z])/gi,"$1-$2")     // "Санкт - Петербург" -> "Санкт-Петербург"
    .replace(/\s{2,}/g," ").replace(/[.,;]+$/,"").trim();
}
function detectLocation(lines){
  for(const raw of lines.slice(0,22)){
    const line=raw.replace(/\s+([,.;:])/g,"$1").trim();
    if(!line) continue;
    const chunks=line.split(/\s*[|·•∙‧]\s*/);                // split combined contact lines
    for(let ch of chunks){
      ch=ch.trim();
      const hadPrefix=LOC_PREFIX_RE.test(ch);
      if(!hadPrefix){                                         // "archvadze89@gmail.com +971502608464 Dubai": the city after the contacts
        const ph=findPhone(ch);
        let rest=ch.replace(EMAIL_G_RE," ").replace(/(https?:\/\/|www\.)\S+/gi," ");
        if(ph) rest=rest.split(ph).join(" ");
        ch=rest.replace(/^[\s,;]+|[\s,;]+$/g,"");
      }
      let cand=hadPrefix ? ch.replace(LOC_PREFIX_RE,"").trim() : ch;
      if(hadPrefix){                                          // keep just the city/region, drop metro & extra clauses
        cand=cand.split(/\s*,\s*/).filter(p=>p && !/^(м\.|метро|ст\.|station|метро)/i.test(p)).slice(0,2).join(", ");
      }
      cand=cand.replace(/\s*[,;]\s*(?=готов|не готов|можно|есть\s|гражданств|разрешение)/i," ").replace(/^[•\-\s|]+/,"").trim();
      cand=tidyLoc(cand);
      const ok = cand && cand.length<=44 && !/гражданств|разрешение/i.test(cand) &&
                 (hadPrefix || looksLikeLocationChunk(cand));
      if(ok) return cand;
    }
  }
  return "";
}

/* ============================ fonts ============================ */
// A font that failed to load must never reach jsPDF: an HTML error page embedded as a "font" breaks the PDF.
async function fetchBase64(url){
  const r = await fetch(url);
  if(!r.ok) throw new Error("font HTTP "+r.status+" "+url);
  const bytes=new Uint8Array(await r.arrayBuffer());
  const sig=String.fromCharCode(bytes[0],bytes[1],bytes[2],bytes[3]);
  if(bytes.length<10000 || !(sig==="\x00\x01\x00\x00" || sig==="true" || sig==="OTTO")) throw new Error("font: not a TrueType file "+url);
  let bin=""; const chunk=0x8000;
  for(let i=0;i<bytes.length;i+=chunk) bin+=String.fromCharCode.apply(null,bytes.subarray(i,i+chunk));
  return btoa(bin);
}
// only a complete, valid set is cached: after a failure the next click goes to the network again
async function ensureFonts(cb){
  if(fontCache) return fontCache;
  if(cb) cb("Загружаю шрифт (кириллица)…",0.1);
  let reg,med,bold;
  try{ [reg,med,bold]=await Promise.all([fetchBase64(FONTS.reg),fetchBase64(FONTS.med),fetchBase64(FONTS.bold)]); }
  catch(e){
    if(cb) cb("",0);
    console.error(e);
    throw new Error("Не загрузился шрифт для PDF. Проверьте интернет и нажмите \"Скачать PDF\" ещё раз.");
  }
  fontCache={reg,med,bold};
  if(cb) cb("",1);
  return fontCache;
}

/* ============================ extraction ============================ */
async function extractFile(file, opts){
  opts=opts||{};
  const name=(file.name||"").toLowerCase();
  if(name.endsWith(".txt")||file.type==="text/plain") return {text:await file.text(), photo:""};
  if(name.endsWith(".pdf")||file.type==="application/pdf") return await extractPdf(file,opts);
  if(name.endsWith(".docx")) return {text:await extractDocx(file), photo:""};
  if(name.endsWith(".doc")) throw new Error("Старый формат .doc не поддерживается - пересохраните как .docx или PDF.");
  if((file.type||"").startsWith("image/")||/\.(png|jpe?g|webp|bmp)$/.test(name)) return await extractImage(file,opts);
  return {text:await file.text(), photo:""};
}

// letters and digits only: a page number or stray icons are not "text"
function textChars(s){ return (String(s||"").match(/[\p{L}\p{N}]/gu)||[]).length; }
const PDF_OCR_MIN_CHARS=50;    // a PDF with less real text than this is a scan / image-only export: OCR its pages
const PDF_OCR_MAX_PAGES=8;

// Where each image is drawn on the page (PDF points), from the operator list: the image fills the unit square of the
// current transform. Used to tell a candidate photo from a page background, a sidebar or a whole scanned page.
function imagePlacements(ops){
  const O=pdfjsLib.OPS, res=[], st=[]; let m=[1,0,0,1,0,0];
  const mul=(a,b)=>[a[0]*b[0]+a[2]*b[1], a[1]*b[0]+a[3]*b[1], a[0]*b[2]+a[2]*b[3], a[1]*b[2]+a[3]*b[3], a[0]*b[4]+a[2]*b[5]+a[4], a[1]*b[4]+a[3]*b[5]+a[5]];
  ops.fnArray.forEach((fn,i)=>{
    const a=ops.argsArray[i];
    if(fn===O.save) st.push(m);
    else if(fn===O.restore){ if(st.length) m=st.pop(); }
    else if(fn===O.transform && a && a.length===6) m=mul(m,a);
    else if(fn===O.paintFormXObjectBegin){ st.push(m); if(a && Array.isArray(a[0]) && a[0].length===6) m=mul(m,a[0]); }
    else if(fn===O.paintFormXObjectEnd){ if(st.length) m=st.pop(); }
    else if(fn===O.paintImageXObject && a && typeof a[0]==="string")
      res.push({name:a[0], w:Math.hypot(m[0],m[1]), h:Math.hypot(m[2],m[3])});
  });
  return res;
}

async function extractPdf(file, opts){
  opts = typeof opts==="function" ? {cb:opts} : (opts||{});
  const cb=opts.cb;
  const data=new Uint8Array(await file.arrayBuffer());
  const pdf=await pdfjsLib.getDocument({data}).promise;
  const out=[], cands=[];
  for(let p=1;p<=pdf.numPages;p++){
    if(cb) cb(`Читаю PDF - страница ${p}/${pdf.numPages}…`, 0.05+0.45*p/pdf.numPages);
    const page=await pdf.getPage(p);
    const vp=page.getViewport({scale:1});
    const tc=await page.getTextContent();
    out.push.apply(out, reconstructLines(tc.items, vp.width));
    out.push("");
    // candidate photos: not icons, not banners / sidebars, not a background or a whole scanned page
    try{
      const ops=await page.getOperatorList();
      for(const pl of imagePlacements(ops)){
        // images shared between pages live in commonObjs ("g_" prefix): page.objs.get never resolves for them (hang)
        const store=pl.name.startsWith("g_")?page.commonObjs:page.objs;
        const img=await Promise.race([
          new Promise(res=>{ try{ store.get(pl.name,res); }catch(e){ res(null); } }),
          new Promise(res=>setTimeout(()=>res(null),4000))   // never block the whole resume on one image
        ]);
        if(!img||!img.width||!img.height) continue;
        const area=img.width*img.height, ar=img.width/img.height;
        if(area<60*60 || ar>2 || ar<0.5) continue;
        const cover=(pl.w*pl.h)/(vp.width*vp.height);
        if(cover>0.4 || pl.w>0.9*vp.width || pl.h>0.9*vp.height) continue;
        let score=Math.min(area, 800*1000);              // a huge picture does not win only by its size
        if(ar>=0.6 && ar<=1.05) score*=2;                // a face crop is square or portrait
        if(p===1) score*=1.5;                            // the photo sits in the header
        cands.push({score,img});
      }
    }catch(e){}
  }
  let text=out.join("\n");
  if(textChars(text)<PDF_OCR_MIN_CHARS && global.Tesseract){
    const ocr=await ocrPdfPages(pdf, opts);
    if(textChars(ocr)>textChars(text)) text=ocr;
  }
  cands.sort((a,b)=>b.score-a.score);
  let photo="";
  for(const c of cands){ photo=imgToDataUrl(c.img); if(photo) break; }
  return { text, photo };
}

// scanned / image-only PDF: render each page and run it through the same OCR as photos of a CV
async function ocrPdfPages(pdf, opts){
  const cb=opts.cb, lang=opts.lang||"eng+rus";
  const n=Math.min(pdf.numPages, PDF_OCR_MAX_PAGES);
  let cur=1;
  const worker=await Tesseract.createWorker(lang,1,{logger:m=>{
    if(cb && m.status==="recognizing text") cb(`Распознаю скан (OCR) - страница ${cur}/${n}…`, 0.5+0.5*((cur-1)+m.progress)/n);
  }});
  const out=[];
  try{
    for(let p=1;p<=n;p++){
      cur=p;
      if(cb) cb(`Распознаю скан (OCR) - страница ${p}/${n}…`, 0.5+0.5*(p-1)/n);
      const page=await pdf.getPage(p);
      const v1=page.getViewport({scale:1});
      const vp=page.getViewport({scale:Math.min(3, 2200/Math.max(v1.width,v1.height))});   // about 190 dpi on A4
      const c=document.createElement("canvas"); c.width=Math.round(vp.width); c.height=Math.round(vp.height);
      const ctx=c.getContext("2d"); ctx.fillStyle="#fff"; ctx.fillRect(0,0,c.width,c.height);
      await page.render({canvasContext:ctx, viewport:vp}).promise;
      const {data}=await worker.recognize(c);
      out.push(data.text||"", "");
    }
  } finally { await worker.terminate(); }
  return out.join("\n");
}

/* column-aware line reconstruction: keeps left date-column with its block */
const DATE_L=/(^|[\s(])(янв|фев|мар|апр|ма[йя]|июн|июл|авг|сен|окт|ноя|дек|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[а-яёa-z.]*\s*\d{4}|^\s*\d{4}\s*[\u2014\u2013\-]|настоящее время|по\s+настоящее|present|^\s*\d+\s*(год|года|лет|month|year|мес)|^\s*(месяц[а-яё]*|года?|лет|год|months?|years?)\s*$/i;
const PERIOD_START=/(\d{4}\s*[\u2014\u2013\-]\s*$)|^((янв|фев|мар|апр|ма[йя]|июн|июл|авг|сен|окт|ноя|дек|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[а-яёa-z.]*\s*\d{4})|^\s*(19|20)\d{2}(\s*[\u2014\u2013\-].*)?$/i;
/* ---- letter-spaced (tracked) text: Canva/designer PDFs, hand-spaced Word headings ---- */
const TRK_CH=/^[\p{L}\p{N}]$/u;
// "O G" / "- J a n" / "2 0 2 5 -" -> "OG" / "- Jan" / "2025 -": glue letters/digits, keep spaces next to punctuation.
// null when s is not a run of single characters split by single spaces.
function glueSpaced(s){
  const toks=s.trim().split(" ");
  if(toks.length<2 || toks.some(t=>t.length!==1)) return null;
  let w=toks[0];
  for(let i=1;i<toks.length;i++) w+=(TRK_CH.test(toks[i-1])&&TRK_CH.test(toks[i])?"":" ")+toks[i];
  return w;
}
// "C u s t o m e r" / "З а к а з ч и к" -> "Customer" / "Заказчик". Only a chunk made entirely of single characters
// with 3+ letters/digits is touched, so "Hepatitis A B C" stays; 2+ spaces are word breaks.
function collapseTracked(s){
  if(!s || !/\S \S/.test(s)) return s;
  return s.split(/(\s{2,})/).map(ch=>{
    const w=glueSpaced(ch);
    if(w===null || (ch.match(/[\p{L}\p{N}]/gu)||[]).length<3) return ch;
    return ch.match(/^\s*/)[0]+splitCamel(w)+ch.match(/\s*$/)[0];
  }).join("");
}
// word breaks lost inside one spaced run come back at lower->Upper joints: "CustomerService" -> "Customer Service";
// short prefixes stay glued (McDonald, DeVito, MacArthur)
function splitCamel(w){
  return w.replace(/(\p{Lu}?\p{Ll}{2,})(?=\p{Lu}\p{Ll})/gu, m=>/^(mac|van|von|del|der|dos|das)$/i.test(m)?m:m+" ");
}
// Separator between neighbouring items comes from geometry instead of a blind " ":
//  - items that touch (gap < 0.1em) are one word cut by the PDF producer: "D"+"irected", "202"+"5", "high"+"-"+"performing";
//  - a run of letter-spaced pieces (single glyphs, caps pairs pdf.js merged by kerning "LT", spaced chunks "S O C I O L")
//    glues together, and only a clearly wider gap inside the run is a word break: "N","A","T",... -> "NATALIA SCULLY".
const GLUE_L=/[\p{L}\p{N}\p{M}\p{Pd}+@\/_]$/u, GLUE_R=/^[\p{L}\p{N}\p{M}\p{Pd}@\/_]/u, WORDY=/[\p{L}\p{N}\p{M}]/u;
function trackKind(s){
  const t=s.trim();
  if(TRK_CH.test(t)) return "g";                                                     // one glyph
  if(/^(?=.*\p{Lu})[\p{Lu}\p{N}] ?[\p{Lu}\p{N}]$/u.test(t)) return "k";             // kerned caps pair: "LT", "A T"
  if(glueSpaced(t)!==null && (t.match(/[\p{L}\p{N}]/gu)||[]).length>=2) return "s"; // spaced chunk: "S O C I O L", "O G"
  return "";
}
function glueRowItems(arr){
  const its=arr.slice().sort((a,b)=>a.x-b.x).map(o=>Object.assign({},o,{k:trackKind(o.s)}));
  const n=its.length; if(!n) return "";
  const em=o=>o.fs||10, gap=i=>its[i].x-(its[i-1].x+its[i-1].w);
  const sep=new Array(n).fill(" ");
  for(let i=1;i<n;i++){
    const a=its[i-1].s, b=its[i].s, e=Math.max(em(its[i-1]),em(its[i])), g=gap(i);
    if(/\s$/.test(a) || /^\s/.test(b) || g>=0.1*e || g<-0.3*e) continue;
    if(i===1 && /^[\p{Pd}•*·▪‣]$/u.test(a)) continue;                              // a leading "-" stays a list marker
    const la=a.slice(-1), fb=b.charAt(0);
    // glue only word-ish joints with a letter/digit on at least one side ("|"+"2010" keeps its space)
    if(GLUE_L.test(la) && GLUE_R.test(fb) && (WORDY.test(la)||WORDY.test(fb)) && !(la==="+" && !/\d/.test(fb))) sep[i]="";
  }
  // typical space between ordinary words of this row (em): a lowercase "run" spaced like that is plain text ("в 2 х раза")
  const plain=[];
  for(let i=1;i<n;i++){ const g=gap(i)/em(its[i]); if((!its[i-1].k || !its[i].k) && g>0.1 && g<1) plain.push(g); }
  plain.sort((x,y)=>x-y);
  const plainGap=plain.length ? plain[plain.length>>1] : 0;
  for(let i=0;i<n;){
    if(!its[i].k){ its[i].s=collapseTracked(its[i].s); i++; continue; }
    const e=em(its[i]);
    let j=i;
    while(j+1<n && its[j+1].k && gap(j+1)<e && gap(j+1)>-0.3*e && Math.abs(em(its[j+1])-e)<0.2*e) j++;
    const run=its.slice(i,j+1), txt=run.map(o=>o.s).join(""), cnt=c=>run.filter(o=>o.k===c).length, gs=[];
    for(let k=i+1;k<=j;k++) gs.push(gap(k));
    const q=Math.max(0, gs.length ? gs.slice().sort((x,y)=>x-y)[(gs.length-1)>>2] : 0);   // letter gap = lower quartile
    let ok=(txt.match(/[\p{L}\p{N}]/gu)||[]).length>=3 && (run.length>=3 || (run.length===2 && cnt("s")>0))
           && cnt("g")+cnt("s")>=Math.max(2,cnt("k"));
    if(ok && /\p{Ll}/u.test(txt)) ok=!cnt("k") && !(plainGap && q/e>=0.75*plainGap);
    if(ok){
      run.forEach(o=>{ if(o.k!=="g") o.s=glueSpaced(o.s)||o.s.replace(/ /g,""); });
      const brk=Math.min(0.55*e, q+Math.max(0.15*e, 0.6*q));      // anything wider than 0.55em is a word break anyway
      for(let k=i+1;k<=j;k++) sep[k]= gap(k)>brk ? " " : "";
    } else run.forEach(o=>{ o.s=collapseTracked(o.s); });
    i=j+1;
  }
  let s=its[0].s; for(let i=1;i<n;i++) s+=sep[i]+its[i].s;
  return s;
}
function joinRowItems(arr){
  return glueRowItems(arr).replace(/\s+/g," ").replace(/\s+([,.;:%)\u00bb])/g,"$1").replace(/([\u00ab(])\s+/g,"$1").trim();
}
// A row with a huge horizontal gap is two separate texts that share a baseline (name on the left, city on the right
// of a designer header; left sidebar + right column): split it so they do not end up as one line.
function splitRowAtGaps(arr){
  const its=arr.slice().sort((a,b)=>a.x-b.x), parts=[[its[0]]];
  for(let i=1;i<its.length;i++){
    const a=its[i-1], b=its[i], g=b.x-(a.x+a.w), e=Math.max(a.fs||10,b.fs||10);
    if(a.w>0 && b.w>0 && g>Math.max(3*e,24)) parts.push([b]); else parts[parts.length-1].push(b);
  }
  return parts;
}
// Column-aware line reconstruction: de-interleaves hh.ru's left meta column (period/degree) from the right
// content column, so each entry reads "period / company / position / description" instead of a scrambled mix.
function reconstructLines(items, pageW){
  const its=[], seen=new Set();
  items.forEach(it=>{
    if(!it.str || !it.str.trim()) return;
    // designer PDFs (Canva etc.) draw the same text 2-3 times at one spot (shadow / outline layers): keep one copy
    const key=Math.round(it.transform[4])+"|"+Math.round(it.transform[5])+"|"+it.str;
    if(seen.has(key)) return; seen.add(key);
    its.push({x:it.transform[4], y:it.transform[5], w:it.width||0, s:it.str,
      fs:it.height||Math.hypot(it.transform[2],it.transform[3])||0}); });
  if(!its.length) return [];
  its.sort((a,b)=> b.y-a.y || a.x-b.x);
  const rows=[]; let cur=null;
  its.forEach(it=>{ if(!cur || Math.abs(cur.y-it.y)>3.2){ cur={y:it.y, its:[]}; rows.push(cur); } cur.its.push(it); });

  // detect the right-column left margin RX
  const h={};
  rows.forEach(r=>{ const minx=Math.min.apply(null,r.its.map(i=>i.x)); if(minx>90 && minx<330){ const b=Math.round(minx/5)*5; h[b]=(h[b]||0)+1; } });
  let RX=0, bc=0; for(const k in h){ if(h[k]>bc){ bc=h[k]; RX=+k; } }
  const leftCount = RX ? its.filter(i=>(i.x+i.w)<RX-8).length : 0;
  if(!RX || bc<4 || leftCount<5)                                          // single column
    return [].concat(...rows.map(r=>splitRowAtGaps(r.its).map(joinRowItems))).filter(Boolean);

  const out=[]; let e=null;
  const flush=()=>{ if(!e) return; out.push("");
    let m=e.meta.join(" ").replace(/\s*[\u2014\u2013\-]\s*$/,"").replace(/\s{2,}/g," ").trim();
    m=m.replace(/\s(\d{1,2}\s+(?:год|года|лет|месяц[а-яё]*).*)$/i," · $1");   // period · duration
    if(m) out.push(m); e.content.forEach(c=>out.push(c)); e=null; };
  for(const r of rows){
    const parts=r.its.slice().sort((a,b)=>a.x-b.x);
    // largest horizontal gap in the row
    let gi=-1, gmax=0;
    for(let i=0;i<parts.length-1;i++){ const g=parts[i+1].x-(parts[i].x+parts[i].w); if(g>gmax){ gmax=g; gi=i; } }
    const splitX = gi>=0 ? parts[gi+1].x : Infinity;
    const twoCol = gi>=0 && gmax>14 && splitX>=RX-26 && splitX<=RX+26 && parts[0].x<RX-12;
    if(twoCol){
      const meta=joinRowItems(parts.slice(0,gi+1)), content=joinRowItems(parts.slice(gi+1));
      if(PERIOD_START.test(meta)){ flush(); e={meta:[meta], content: content?[content]:[]}; }
      else if(e && e.meta.length<4 && !isHeader(meta)){ e.meta.push(meta); if(content) e.content.push(content); }
      else { flush(); out.push(meta); if(content) out.push(content); }   // hh.ru meta is 1-3 short lines; more is a sidebar
    } else {
      const line=joinRowItems(parts);
      const rightOnly = parts.every(p=>p.x>=RX-8);
      const leftOnly  = parts.every(p=>(p.x+p.w)<RX-6);
      if(rightOnly){ if(e) e.content.push(line); else out.push(line); }
      else if(leftOnly && e && e.meta.length<4 && !isHeader(line) && (DATE_L.test(line)||line.length<26)){ e.meta.push(line); }
      else { flush(); out.push(line); }   // heading or full-width prose
    }
  }
  flush();
  return out.filter((l,i,a)=> !(l===""&&(a[i-1]===""||i===0)) );
}

function imgToDataUrl(im, maxW){
  try{
    maxW = maxW || 320;
    const scale = im.width>maxW ? maxW/im.width : 1;
    const w=Math.round(im.width*scale), h=Math.round(im.height*scale);
    const c=document.createElement("canvas"); c.width=w; c.height=h;
    const ctx=c.getContext("2d");
    if(im.bitmap){ ctx.drawImage(im.bitmap,0,0,w,h); }
    else if(im.data){
      const tmp=document.createElement("canvas"); tmp.width=im.width; tmp.height=im.height;
      const tctx=tmp.getContext("2d");
      const id=tctx.createImageData(im.width,im.height); const d=im.data;
      if(d.length===im.width*im.height*3){ for(let i=0,j=0;i<d.length;i+=3,j+=4){ id.data[j]=d[i];id.data[j+1]=d[i+1];id.data[j+2]=d[i+2];id.data[j+3]=255; } }
      else if(d.length===im.width*im.height*4){ id.data.set(d); }
      else return "";
      tctx.putImageData(id,0,0);
      ctx.drawImage(tmp,0,0,w,h);
    } else return "";
    if(isFlatCanvas(c)) return "";      // an all-white / one-colour picture is a placeholder, not a photo
    return c.toDataURL("image/jpeg",0.78);
  }catch(e){ return ""; }
}
function isFlatCanvas(c){
  try{
    const s=document.createElement("canvas"); s.width=24; s.height=24;
    const x=s.getContext("2d"); x.drawImage(c,0,0,24,24);
    const d=x.getImageData(0,0,24,24).data; let n=0, sum=0, sq=0;
    for(let i=0;i<d.length;i+=4){ const v=0.3*d[i]+0.59*d[i+1]+0.11*d[i+2]; sum+=v; sq+=v*v; n++; }
    const mean=sum/n; return Math.sqrt(Math.max(0, sq/n-mean*mean))<4;
  }catch(e){ return false; }
}

async function extractDocx(file){
  const r=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});
  return r.value;
}
async function extractImage(file, opts){
  const lang=(opts && opts.lang) || "eng+rus";
  const worker=await Tesseract.createWorker(lang,1,{logger:m=>{
    if(opts&&opts.cb&&m.status==="recognizing text") opts.cb("Распознаю текст (OCR)…",0.1+m.progress*0.9);
  }});
  const {data}=await worker.recognize(file);
  await worker.terminate();
  return {text:data.text, photo:""};
}

/* ============================ cleaning ============================ */
function cleanText(text, on){
  on = on!==false;
  let lines=text.replace(/\r/g,"").split("\n").map(collapseTracked);   // "Р Е З Ю М Е" typed by hand in Word, OCR of tracked headings
  const out=[];
  for(let raw of lines){
    let ln=raw.replace(/ /g," ").replace(/[ \t]+/g," ").trimEnd();
    ln=ln.replace(/\s+([,.;:%])/g,"$1");          // fix hh.ru spaced punctuation
    // control characters from broken PDF fonts: "2024 \u0000 2025" is a dash, a lone one is an icon
    ln=ln.replace(/(\d)\s*\u0000\s*(\d)/g,"$1 - $2").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F�]/g,"");
    if(on){
      if(isWatermarkLine(ln)) continue;
      const tail=ln.replace(STAMP_TAIL_RE,"").trimEnd();
      if(tail!==ln.trimEnd()){ if(textChars(tail)<3) continue; ln=tail; }
      if(SRC_RE.test(ln)){
        // a line that is only a link / handle to a job-board or data-vendor profile: "linkedin.com/in/ivan", "www.hh.ru/resume/1"
        if(/(https?:\/\/|www\.|\.(com|ru|io|net|co|me|org|ae|in|ua|ge)\b)/i.test(ln) && ln.trim().split(/\s+/).length<=3) continue;
        // inside a line only LINKS to such sites and "downloaded from / via X" tails go; the name itself stays
        // ("Managed LinkedIn Recruiter seats", "Recruiter | Bayt.com | 2016", "Senior Headhunter")
        let s=ln.split(" ").filter(tok=>!(SRC_RE.test(tok) && (/^\(?(https?:\/\/|www\.)/i.test(tok) || /\.[a-z]{2,6}\/\S/i.test(tok)))).join(" ");
        s=s.replace(SRC_TAIL_RE,"");
        if(s!==ln){
          s=s.replace(/([|·•])\s*(?:[|·•]\s*)+/g,"$1 ").replace(/^\s*[|·,;:]+\s*/,"").replace(/[\s|·•,;:\p{Pd}]+$/u,"").replace(/\s{2,}/g," ").trimEnd();
        }
        // the line was only a source mention or an empty template label: "LinkedIn", "(hh.ru)", "LinkedIn/Portfolio"
        let rest=s.replace(SRC_RE_G,"");
        if(s.split(/\s+/).length<=4) rest=rest.replace(/(?<![\p{L}])(?:portfolio|profile|website|site|link|url|page|resume|cv|профиль|ссылка|сайт|страница|резюме)(?![\p{L}])/giu,"");
        if(textChars(rest)<3) continue;
        ln=s;
      }
    }
    out.push(ln);
  }
  return out.join("\n").replace(/\n{3,}/g,"\n\n").trim();
}

/* ============================ parsing ============================ */
const HEAD_TAIL=new Set(["and","&","of","the","training","information","info","history","summary","details","background","section","skills","experience","education","и","или"]);
function isHeader(line){
  let t=line.trim().replace(/\s*[:：]\s*$/,"");           // tolerate a trailing colon
  if(!t) return null;
  // strip an hh.ru duration tail ("- 13 лет 5 месяцев") before structural checks
  const core=t.replace(/\s*[\u2014\-\u2013]\s*\d+\s*(год\w*|лет|year\w*|month\w*|мес\w*).*$/i,"").trim();
  if(!core||core.length>40) return null;
  if(/[,;]|[•·|]/.test(core)) return null;                // headers carry no commas or bullet separators
  if(core.split(/\s+/).length>6) return null;
  for(const [re,label] of HEAD_MAP){
    const m=core.match(re);
    if(!m) continue;
    const rest=core.slice(m[0].length).trim();
    if(!rest) return label;                               // keyword == whole line
    const restWords=rest.toLowerCase().split(/\s+/).filter(Boolean);
    if(restWords.every(w=>HEAD_TAIL.has(w))) return label; // "Education and training", "Top Skills"
  }
  return null;
}
// An ALL-CAPS line that names a resume block ("ОПЫТ ВОЖДЕНИЯ", "ПРОФЕССИОНАЛЬНЫЙ ПРОФИЛЬ", "DRIVING LICENSE AND LANGUAGES")
// is a section header even when it is not in HEAD_MAP. Caps job titles ("PROFESSIONAL DRIVER", "ОПЫТНЫЙ ВОДИТЕЛЬ")
// do not start with one of these phrases, so they stay in the text. Used only after the name block.
const CAPS_HEAD_RE=/^(опыт\s+\p{L}+|профессиональн\p{L}*\s+(профиль|опыт|навыки|качества|достижения|компетенции)|ключевые\s+\p{L}+|навыки|образование|обучение|водительск\p{L}*\s+(удостоверение|права)|удостоверени\p{L}*|языки|знание\s+языков|личные\s+(качества|данные)|личная\s+информация|дополнительн\p{L}*|сертификаты|курсы|достижения|квалификация|компетенции|о\s+себе|профиль|волонт\p{L}*|summary|profile|professional\s+(summary|profile|experience|skills|background|qualifications|development)|driving\s+(experience|licen[cs]es?|record)|licen[cs]es?|languages?|education|experience|skills|certifications?|courses|achievements|additional\s+information|personal\s+(details|information|qualities)|about\s+me|objective|qualifications|career\s+(summary|objective|history)|references|interests|hobbies|volunteer\p{L}*)(?![\p{L}])/iu;
// Russian and service job titles (JOB_TITLE_RE uses \b, which never matches next to Cyrillic letters)
const JOB_RU_RE=/(?<![\p{L}])(водител|шофер|повар|шеф-повар|официант|бармен|бариста|няня|горничн|уборщи|охранни|продав|кассир|курьер|механик|электрик|сантехник|сварщик|косметолог|массажист|парикмахер|стилист|врач|медсестр|медбрат|менеджер|директор|руководител|специалист|инженер|бухгалтер|администратор|консультант|аналитик|дизайнер|разработчик|программист|маркетолог|ассистент|секретар|оператор|кладовщик|грузчик|помощни|агент|рекрутер|юрист|переводчик|учител|преподавател|тренер|экономист|логист)(?:ь|я|и|ей|ем|ы|а|у|ом|ая|ой|ый|к|ка|ки|ца|цы|ец|щица)?(?![\p{L}])/iu;   // endings only: surnames like "Поварова", "Механиков" stay names
const CAPS_TAIL=new Set(["&","/","proficiency","language","languages","licence","license","licences","licenses","certificates",
  "certifications","courses","achievements","awards","qualities","record","qualifications","интересы","языки","навыки","качества",
  "курсы","сертификаты","достижения","права","удостоверение","данные","информация","компетенции","опыт","хобби"]);
function capsHeader(line){
  const t=line.trim().replace(/\s*:\s*$/,"");
  if(!t || t.length>45 || /\d/.test(t) || /\p{Ll}/u.test(t) || (t.match(/\p{Lu}/gu)||[]).length<4) return null;
  if(t.split(/\s+/).length>5 || /[,;|•·]/.test(t)) return null;
  const m=t.match(CAPS_HEAD_RE);
  if(!m) return null;
  // the rest may only be connecting / heading words: "И ЯЗЫКИ", "PROFICIENCY"; "EDUCATION MANAGEMENT PROFESSIONAL" is a job title
  const rest=t.slice(m[0].length).toLowerCase().split(/\s+/).filter(Boolean);
  if(!rest.every(w=>HEAD_TAIL.has(w) || CAPS_TAIL.has(w))) return null;
  const low=t.toLowerCase();
  return low.charAt(0).toUpperCase()+low.slice(1);
}
// a labelled contact row: "Phone number: +971...", "Email address: x@y.com", "Address: Dubai", "Телефон: ..."
const CONTACT_LABEL_RE=/^(?:phone|tel|telephone|mobile|mob|cell|whatsapp|telegram|e-?mail|address|location|website|linkedin|телефон|тел|моб\p{L}*|почта|адрес|сайт)(?:\s+\p{L}+)?\s*[:.]/iu;
function isContactLine(tt){
  if(!tt) return false;
  if(EMAIL_RE.test(tt) && tt.length<70) return true;
  if(/^[+(]?\d[\d\s().\-]{7,}\d$/.test(tt) && !/^(19|20)\d{2}\s*\p{Pd}\s*(19|20)\d{2}$/u.test(tt)) return true;   // "2018 - 2024" is a period
  if(/^((https?:\/\/)?(www\.)?[a-z0-9.\-]+\.[a-z]{2,}(\/\S*)?)$/i.test(tt) && !/\s/.test(tt)) return true;
  return false;
}
// contact line already shown in the header (same e-mail / same phone digits); bare URLs are dropped as before
function isHeaderContact(tt,res){
  const e=tt.match(EMAIL_RE), dg=s=>(s||"").replace(/\D/g,"");
  if(e) return !!res.email && e[0].toLowerCase()===res.email.toLowerCase();
  if(/^[+(]?\d[\d\s().\-]{7,}\d$/.test(tt)) return !!res.phone && dg(tt)===dg(res.phone);
  return true;
}
// a sentence, not a contact entry: long, or a short phrase with function words ("Brazil, and the UAE.")
const FUNC_WORD=/(?<![\p{L}])(and|the|with|for|of|in|to|an|on|at|by|from|и|в|с|на|по|для|от|до|за|из)(?![\p{L}])/iu;
function isProseLine(c){
  const t=(c||"").trim(), w=t.split(/\s+/).length;
  if(!t || EMAIL_RE.test(t) || findPhone(t) || /https?:|www\./i.test(t) || PERSONAL_RE.test(t)) return false;
  return (t.length>=40 && w>=4) || (w>=3 && FUNC_WORD.test(t));
}
function isLocationLine(tt){
  if(tt.length>=55 || /\d{4}/.test(tt) || EMAIL_RE.test(tt)) return false;
  if(/гражданств|разрешение на работу/i.test(tt)) return false;
  return /(dubai|abu dhabi|sharjah|ajman|uae|united arab emirates|qatar|doha|riyadh|jeddah|kuwait|москва|moscow|санкт|петербург|липецк|самара|екатеринбург|новосибирск|казань|россия|russia|казахстан|алматы|астана|astana|almaty|проживает)/i.test(tt);
}
function looksLikeName(line){
  const t=line.trim();
  if(!t||t.length>48) return false;
  if(/\d|@|http|www\.|\+?\d{5}/.test(t)) return false;
  if(/^(resume|cv|curriculum vitae|резюме)\s*$/i.test(t)) return false;
  if(isHeader(t)||PERSONAL_RE.test(t)) return false;
  const words=t.split(/\s+/);
  if(words.length<1||words.length>4) return false;
  const letters=t.replace(/[^a-zа-яё]/ig,"").length;
  return letters>=t.replace(/\s/g,"").length*0.7;
}

// hh.ru experience: each job starts with a period line like "Ноябрь 2024 -" - add a blank line between jobs for readability
function spaceExperienceEntries(body){
  const startRe=/^[А-ЯЁA-Z][а-яёa-z]+\.?\s+\d{4}\s*[\u2014\u2013-]\s*$/;
  const lines=body.split("\n"), out=[]; let seen=false;
  for(const l of lines){
    if(startRe.test(l.trim())){
      if(seen && out.length && out[out.length-1].trim()!=="") out.push("");
      seen=true;
    }
    out.push(l);
  }
  return out.join("\n");
}
function parseResume(text){
  const lines=text.split("\n");
  const res={name:"",head:"",email:"",phone:"",loc:"",link:"",personal:"",sections:[]};

  const em=text.match(EMAIL_RE); if(em) res.email=em[0];
  res.phone=findPhone(text);
  const linkM = text.match(/(?:https?:\/\/)?(?:www\.)?(?:github|gitlab|behance|dribbble|medium|stackoverflow)\.[a-z]{2,}\/[A-Za-z0-9_\-./]+/i) || text.match(/\bt\.me\/[A-Za-z0-9_]+/i);
  if(linkM) res.link=linkM[0].replace(/[.,;]+$/,"");
  res.loc = detectLocation(lines);

  // personal facts (hh.ru top block)
  const personal=[];
  for(const l of lines.slice(0,14)){
    const t=l.trim(); if(!t) continue;
    // facts sit above the first real section: "Увеличил продажи на 45% за 2 года" under "Опыт работы" / "О себе" is not one
    const hh=isHeader(t)||capsHeader(t);
    if(hh && !/^(Желаемая должность|__PERSONAL__|__CONTACTS__)$/.test(hh)) break;
    if(/^[•*·▪-]/.test(t)) continue;                        // a list item is an achievement, not a personal fact
    if(PERSONAL_RE.test(t) && !isHeader(t) && t.length<90) personal.push(t);
  }
  res.personal=[...new Set(personal)].join("\n");

  let i=0;
  while(i<lines.length && !lines[i].trim()) i++;
  if(i<lines.length && /^(resume|cv|curriculum vitae|резюме)\s*$/i.test(lines[i].trim())) i++;
  while(i<lines.length && !lines[i].trim()) i++;
  const start=i;
  let pendingHead="", pendingIdx=-1;
  // name is valid only above any section header / personal-facts block (hh.ru exports often omit the name)
  for(let k=start;k<Math.min(start+12,lines.length);k++){
    const t=(lines[k]||"").trim();
    if(!t) continue;
    if(CONTACT_LABEL_RE.test(t)) continue;                   // "Phone number: +971..." printed above the name (two-column header)
    const h=isHeader(t)||capsHeader(t);
    if(h==="__CONTACTS__"||h==="__PERSONAL__") continue;   // skip hh.ru "Способы связаться"/contact labels - the name may sit just after
    if(h||PERSONAL_RE.test(t)) break;
    if(t.includes(",") && looksLikeLocationChunk(t)) continue;      // "Дубай, ОАЭ" printed under the title is not a name
    if(looksLikeName(t)){
      // job title sitting above the name (or instead of it) -> headline; names carry no "/"
      if((JOB_TITLE_RE.test(t) || JOB_RU_RE.test(t) || t.includes("/")) && !pendingHead){ pendingHead=t; pendingIdx=k; continue; }
      res.name=t; i=k+1; break;
    }
    if(!isContactLine(t)) break;   // first real non-name, non-contact line -> no name here
  }
  // first and last name on two lines ("DURDYHAL" / "JUMAKULYYEVA", "Takudzwa" / contacts / "Munotengwa"): join them
  if(res.name && !/\s/.test(res.name)){
    const upper=s=>s===s.toUpperCase();
    for(let j=i;j<Math.min(i+5,lines.length);j++){
      const t=(lines[j]||"").trim();
      if(!t || isContactLine(t) || CONTACT_LABEL_RE.test(t)) continue;
      if(/^\p{Lu}[\p{L}'-]{1,29}$/u.test(t) && upper(t)===upper(res.name) && !isHeader(t) && !capsHeader(t) && !jobLike(t)
         && !looksLikeLocationChunk(t) && !PERSONAL_RE.test(t)){
        res.name+=" "+t; lines[j]=""; if(j===i) i=j+1;
      }
      break;
    }
  }
  // headline = line right after a found name
  if(res.name){
    for(let k=i;k<Math.min(i+4,lines.length);k++){
      const t=(lines[k]||"").trim();
      if(!t) continue;
      if(EMAIL_RE.test(t)||PHONE_RE.test(t)||isHeader(t)||capsHeader(t)||PERSONAL_RE.test(t)) break;
      if(res.loc && tidyLoc(t)===res.loc) continue;          // city printed next to the name is not the headline
      if(t.length<=70 && !/[•|]/.test(t)){ res.head=t; i=k+1; }
      break;
    }
    // a short headline wrapped onto a second line by the layout: "Customer" / "Representative"
    const nx=(lines[i]||"").trim();
    if(res.head && /^[\p{L}\s]+$/u.test(res.head) && res.head.split(/\s+/).length<=2 && /^\p{Lu}\p{L}{2,19}$/u.test(nx)
       && !isHeader(nx) && !PERSONAL_RE.test(nx) && !looksLikeLocationChunk(nx)){ res.head+=" "+nx; i++; }
    if(!res.head && pendingHead) res.head=pendingHead;
  } else if(pendingHead){ res.head=pendingHead; i=pendingIdx+1; }   // no name in the file (blind export): the title is the headline
  else { i=start; }

  let cur={title:"",body:[]};
  const flush=()=>{ if(cur.title||cur.body.join("").trim()){ res.sections.push({title:cur.title,body:cur.body.join("\n").trim()}); } };
  let started=false;
  const absorbed=new Set();
  for(let k=i;k<lines.length;k++){
    if(absorbed.has(k)) continue;
    const t=lines[k];
    const h=isHeader(t)||capsHeader(t);
    if(h){
      if(h==="__CONTACTS__" || h==="__PERSONAL__"){
        for(let j=k+1; j<lines.length; j++){
          const c=lines[j]; if(isHeader(c)||capsHeader(c)) break;
          // two-column layouts interleave the neighbour column's sentences into a contacts block: leave them in the flow
          if(h==="__CONTACTS__" && isProseLine(c)) continue;
          absorbed.add(j);
          if(!c.trim()) continue;
          if(!res.email){const e=c.match(EMAIL_RE);if(e)res.email=e[0];}
          if(!res.phone) res.phone=findPhone(c);
          if(h==="__CONTACTS__" && looksLikeLocationChunk(c) && !/(^|[\s,])(м\.|метро|ст\.|station)/i.test(c)){   // "Al Furjan, Dubai, UAE" beats "Dubai, UAE"
            const lc=tidyLoc(c);
            if(!res.loc || (lc.length>res.loc.length && lc.toLowerCase().includes(res.loc.toLowerCase()))) res.loc=lc;
          }
          if(h==="__PERSONAL__"){
            const pl=c.replace(/^[•\-\s]+/,"").trim();
            if(pl && !EMAIL_RE.test(c) && !/^(https?:|www\.)|@/i.test(pl) && pl.length<90)
              res.personal=(res.personal?res.personal+"\n":"")+pl;
          }
        }
        continue;         // absorbed lines are skipped by the main loop
      }
      if(started) flush();
      cur={title:h,body:[]}; started=true;
    } else {
      const tt=t.trim();
      if(isContactLine(tt) && isHeaderContact(tt,res)) continue;   // a second e-mail / phone stays in the text
      if(!started && (tt==="" || isLocationLine(tt) || PERSONAL_RE.test(tt) || (res.loc && tt===res.loc))) continue;
      if(!started){ cur.title=res.name&&/[а-яё]/i.test(res.name)?"Профиль":"Profile"; }
      cur.body.push(t);
      started=true;
    }
  }
  flush();
  res.sections=res.sections.map(s=>({title:s.title,body:s.body.replace(/\n{3,}/g,"\n\n").trim()}));
  // merge all sections sharing a title into the first occurrence (hh.ru repeats e.g. "Навыки", "Образование")
  const merged=[], idx={};
  res.sections.forEach(s=>{
    if(s.title && idx[s.title]!=null){ merged[idx[s.title]].body=(merged[idx[s.title]].body+"\n"+s.body).trim(); }
    else { if(s.title) idx[s.title]=merged.length; merged.push({title:s.title,body:s.body}); }
  });
  res.sections=merged;
  // hh.ru "Желаемая должность" -> use its first line as the headline (no duplication)
  if(!res.head){
    const ds=res.sections.find(s=>/желаемая должность|desired position/i.test(s.title));
    if(ds){ const bl=ds.body.split("\n"); res.head=(bl.shift()||"").trim(); ds.body=bl.join("\n").trim();
      res.head=res.head.replace(/\s+\d[\d\s]{3,}\s*(₽|руб|\$|€|aed|usd|eur|dirham|дирхам).*$/i,"").replace(/\s*(на руки|до вычета налогов).*$/i,"").trim(); }
  }
  res.sections=res.sections.map(s=>/(опыт|experience)/i.test(s.title)?{title:s.title,body:spaceExperienceEntries(s.body)}:s);
  res.sections=res.sections.filter(s=>s.body.length>0);
  if(res.personal) res.personal=[...new Set(res.personal.split("\n").map(s=>s.trim()).filter(Boolean))].join("\n");
  return res;
}

/* ============================ layout model (shared by the PDF and the HTML preview) ============================ */
// A section body becomes blocks that both renderers draw the same way:
//   p     paragraph (lines wrapped by the source PDF are joined back into one paragraph)
//   li    bullet item (its wrapped continuation lines joined)
//   sub   ALL-CAPS sub-heading inside a section
//   kv    "Label: value" line (label in bold)
//   entry job / education header: title, place and period (period goes to the right edge)
//   role  a short position line right under an entry header
//   grid  short items of a skills / languages section: chips or two columns
//   gap   blank line between groups
const GUIL_RE=new RegExp("["+String.fromCharCode(171,187)+"]","g");
const ARROW_RE=new RegExp("["+String.fromCharCode(0x2190)+"-"+String.fromCharCode(0x21FF)+String.fromCharCode(0x27F5)+"-"+String.fromCharCode(0x27FF)+"]","g");
// agency house style: plain hyphen instead of long dashes, straight quotes, no arrows
function normText(s){
  return String(s||"").replace(/\r/g,"").replace(/[^\S\n]+/g," ").replace(/\p{Pd}/gu,"-").replace(GUIL_RE,'"').replace(ARROW_RE,"-");
}
const MON_P="(?<![\\p{L}])(?:янв|фев|мар|апр|ма[йя]|июн|июл|авг|сен|окт|ноя|дек|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\\p{L}*\\.?";
const YR_P="(?<!\\d)(?:19|20)\\d{2}(?!\\d)";
const NOW_P="(?:по\\s+)?(?:настоящее\\s+время|наст\\.\\s*вр\\p{L}*\\.?|н\\.\\s?в\\.|сейчас|present|current|now|today|till\\s+date)";
const PT_P=`(?:${MON_P}\\s*${YR_P}|\\d{1,2}[./]${YR_P}|${YR_P})`;
const RANGE_RE=new RegExp(`${PT_P}\\s*(?:-|to|по|до)\\s*(?:${PT_P}|${NOW_P})`,"iu");
const MONYR_RE=new RegExp(`${MON_P}\\s*${YR_P}`,"iu");
const NOW_RE=new RegExp(NOW_P,"iu");
const YEAR_RE=new RegExp(YR_P,"u");
const DATE_TAIL_RE=new RegExp(`\\(?(?:${PT_P}|${NOW_P})(?:\\s*(?:-|to|по|до)\\s*(?:${PT_P}|${NOW_P}))?\\)?\\s*$`,"iu");
const DATE_SPAN_RE=new RegExp(`(?:${PT_P})(?:\\s*(?:-|to|по|до)\\s*(?:${PT_P}|${NOW_P}))?`,"iu");
const DUR_RE=/(?<![\p{L}\d])\d+(?:[.,]\d)?\s*(?:год\p{L}*|лет|мес\p{L}*|years?|yrs?|months?|mos?)(?![\p{L}])/iu;
// list markers: round/square bullets, check marks, pointers and the Symbol/Wingdings glyphs Word exports keep
const BULLET_CHARS="•●◦▪■‣·*✓✔"+String.fromCharCode(0x27A2,0x27A4,0x25BA,0x25B6,0x2043,0x2219,0x25E6,0xF0B7,0xF0A7,0xF076,0xF0D8,0xF0FC);
const BUL_RE=new RegExp("^(?:["+BULLET_CHARS+"]\\s*|-\\s+)","u");
const JOB_EN_RE=/(?<![\p{L}])(driver|chauffeur|chef|cook|waiter|waitress|barista|bartender|nanny|housekeeper|cleaner|guard|cashier|courier|receptionist|assistant|operator|worker|therapist|stylist|hairdresser|beautician|cosmetologist|teacher|tutor)(?![\p{L}])/iu;
const jobLike=t=>JOB_TITLE_RE.test(t)||JOB_RU_RE.test(t)||JOB_EN_RE.test(t);
const KV_RE=/^([\p{L}][\p{L}\p{N} /&().'+-]{0,32}?):\s+(\S.*)$/u;
const GRID_T=/(skill|навык|компетенц|competenc|expertise|strength|умени|сильн|качеств|tools|инструмент|software|программ|technolog|технолог|stack|стек|language|язык)/i;
const SUMM_T=/(summary|profile|about|objective|о себе|обо мне|профиль|цель)/i;

function kvParts(t){
  const m=t.match(KV_RE);
  if(!m || m[1].trim().split(/\s+/).length>4 || /https?|www/i.test(m[1])) return null;
  return {k:m[1].trim(), v:m[2].trim()};
}
function isMeta(t){
  if(t.length>90 || /[.!?;:,]$/.test(t) || t.split(/\s+/).length>14 || kvParts(t)) return false;
  if(RANGE_RE.test(t) || MONYR_RE.test(t)) return true;
  const sep=/[|·•]/.test(t);
  if(NOW_RE.test(t) && (YEAR_RE.test(t)||sep)) return true;
  if(DUR_RE.test(t) && sep) return true;
  return YEAR_RE.test(t) && (sep || /^\(?\s*(19|20)\d{2}\s*\)?$/.test(t) || /[,(]\s*(19|20)\d{2}\s*\)?$/.test(t));
}
function isCapsSub(t){
  if(t.length>60 || /\d/.test(t) || /\p{Ll}/u.test(t) || (t.match(/\p{Lu}/gu)||[]).length<4) return false;
  return t.split(/\s+/).length<=7 && /^[\p{Lu}\s&/,.'()"+-]+$/u.test(t) && !/[.,]$/.test(t);
}
function lineKind(t){
  if(!t) return "gap";
  if(BUL_RE.test(t)) return t.replace(BUL_RE,"").trim() ? "li" : "gap";
  if(isMeta(t)) return "meta";
  if(isCapsSub(t)) return "sub";
  if(kvParts(t)) return "kv";
  if(/:$/.test(t) && t.length<=60) return "lead";      // "Ключевые достижения:", "1. Этап открытия шоу-рума:"
  return "text";
}
function splitMeta(t){
  const date=[], place=[];
  t.split(/\s*[|·•]\s*/).filter(Boolean).forEach(p=>
    (RANGE_RE.test(p)||MONYR_RE.test(p)||NOW_RE.test(p)||DUR_RE.test(p)||YEAR_RE.test(p) ? date : place).push(p));
  if(date.length===1 && !place.length){            // "Emirates NBD, Jan 2020 - Present": the period is cut off the tail
    const m=date[0].match(DATE_TAIL_RE);
    if(m && m.index>0){ const head=date[0].slice(0,m.index).replace(/[\s,(-]+$/,""); if(head) place.push(head); date[0]=m[0].replace(/^\(|\)$/g,""); }
    else if(!m){                                   // "May 2023 - Hortman clinics, Dubai": the period is cut off the head
      const s=date[0].match(DATE_SPAN_RE);
      if(s){
        const rest=(date[0].slice(0,s.index)+" "+date[0].slice(s.index+s[0].length)).replace(/^[\s,|()-]+|[\s,|()-]+$/g,"").replace(/\s{2,}/g," ");
        if(rest){ place.push(rest); date[0]=s[0]; }
      }
    }
  }
  return { date:date.join(" · ").replace(/\s*-\s*/g," - ").replace(/\s{2,}/g," ").trim(), place:place.join(" · ") };
}
// a list marker extracted as its own line ("text" / "•") belongs to the line before it when the body ends with such a
// marker (the glyph sat lower than its text), otherwise to the line after it
function fixLoneBullets(lines){
  const lone=l=>!!l && l.length===1 && (BULLET_CHARS.includes(l) || l==="-");
  if(!lines.some(lone)) return lines;
  const ne=lines.filter(Boolean), after=lone(ne[ne.length-1]);
  const out=lines.slice();
  for(let i=0;i<out.length;i++){
    if(!lone(out[i])) continue;
    const step=after?-1:1;
    for(let j=i+step;j>=0 && j<out.length;j+=step){
      if(!out[j]) continue;
      if(!lone(out[j]) && !BUL_RE.test(out[j])) out[j]="• "+out[j];
      break;
    }
    out[i]=null;
  }
  return out.filter(l=>l!==null);
}
// Lines the source layout wrapped are joined back: a paragraph or a bullet becomes one logical line.
// kinds are taken from the normalized text, the output keeps the caller's characters.
function reflowLines(lines){
  const L=lines.map(t=>({t, k:lineKind(normText(t).trim())}));
  const lens=L.filter(o=>o.k==="text"||o.k==="li").map(o=>o.t.length);
  const maxLen=lens.length?Math.max.apply(null,lens):0;
  // a line the source layout wrapped at the right margin; lists of shorter items without markers stay separate
  const full=n=>maxLen>=45 && n>=0.85*maxLen;
  const out=[]; let prevRaw="";
  for(let i=0;i<L.length;i++){
    const o=L[i], last=out[out.length-1];
    if(o.k==="text" && last && (last.k==="li"||last.k==="text"||last.k==="kv")){
      const lower=/^[\p{Ll}(]/u.test(o.t);
      if(lower || (last.k!=="kv" && full(prevRaw.length) && !/[.!?]$/.test(prevRaw) && !(L[i+1] && L[i+1].k==="meta"))){
        last.t+=(/\p{L}-$/u.test(last.t)?"":" ")+o.t; last.one=false; prevRaw=o.t; continue;
      }
    }
    out.push({t:o.t, k:o.k, one:true}); prevRaw=o.k==="gap"?"":o.t;
  }
  return out;
}
function reflowText(body){ return reflowLines(String(body||"").split("\n").map(l=>l.trim())).map(o=>o.t).join("\n"); }
function structureLines(lines){
  const L=reflowLines(lines);
  const short=t=>t.length<=100 && !/[.!?;]$/.test(t);
  const titleLike=b=>b && ((b.t==="p" && b.one) || b.t==="sub") && short(b.text);
  const out=[]; let last=null, afterEntry=false;
  for(let i=0;i<L.length;i++){
    const {t,k,one}=L[i];
    if(k==="gap"){
      // a blank line inside a list is a page break of the source PDF, not a new group
      const nx=L.slice(i+1).find(o=>o.k!=="gap");
      if(last && last.t==="li" && nx && nx.k==="li") continue;
      if(out.length && out[out.length-1].t!=="gap") out.push({t:"gap"});
      last=null; afterEntry=false; continue;
    }
    if(k==="meta"){
      const m=splitMeta(t); let title="", sub="";
      // the entry title sits above the period line ("Driver / Туркменистан | 2017 - 2023") or right under it
      // ("Company | 2010 - 2025 / General Manager"); when both are possible the one that reads like a job title wins
      const nx=L[i+1];
      const canBack=titleLike(out[out.length-1]);
      // a company line may end with a period ("NICEHAIR (бьюти-бренд, Россия и Дубай).") but is one short sentence
      const canFwd=!!nx && (nx.k==="text"||nx.k==="sub") && nx.one && nx.t.length<=80 && short(nx.t.replace(/\.$/,"")) && !/\.\s/.test(nx.t);
      const back=canBack && (!canFwd || jobLike(out[out.length-1].text) || !jobLike(nx.t));
      if(back){
        title=out.pop().text;
        const b=out[out.length-1], before=out[out.length-2];
        if(titleLike(b) && (b.t==="sub" || !before || before.t==="gap" || before.t==="entry")){ sub=title; title=out.pop().text; }
      } else if(canFwd){
        title=L[++i].t.replace(/\.$/,"");
        const n=L[i+1];
        if(n && n.k==="text" && (looksLikeLocationChunk(n.t) || /\.[a-z]{2,}(\/|$)/i.test(n.t))){ sub=n.t; i++; }
      }
      if(m.place) sub = sub ? sub+" · "+m.place : m.place;
      out.push({t:"entry", title, sub, date:m.date}); last=null; afterEntry=true; continue;
    }
    if(k==="text" && afterEntry && one && t.length<=70 && short(t) && !/^[\p{Ll}]/u.test(t)){
      out.push({t:"role", text:t}); afterEntry=false; last=null; continue;
    }
    afterEntry=false;
    if(k==="sub"){ out.push({t:"sub", text:t}); last=null; continue; }
    if(k==="lead"){ out.push({t:"lead", text:t}); last=null; continue; }
    if(k==="li"){ last={t:"li", text:t.replace(BUL_RE,"").trim()}; out.push(last); continue; }
    if(k==="kv"){ const kv=kvParts(t); last={t:"kv", k:kv.k, text:kv.v}; out.push(last); continue; }
    last={t:"p", text:t, one}; out.push(last);
  }
  while(out.length && out[out.length-1].t==="gap") out.pop();
  while(out.length && out[0].t==="gap") out.shift();
  return out;
}
// short items of a skills / languages section -> chips (short) or a two-column list (longer)
function gridItems(title, blocks){
  if(!GRID_T.test(title)) return null;
  const bs=blocks.filter(b=>b.t!=="gap");
  let items=null;
  if(bs.length>=4 && bs.every(b=>(b.t==="li" || (b.t==="p" && b.one)) && b.text.length<=110)
     && bs.filter(b=>b.text.length<=60).length>=bs.length*0.75) items=bs.map(b=>b.text);
  else if(bs.length && bs.length<=3 && bs.every(b=>b.t==="p"||b.t==="li")){
    const parts=bs.map(b=>b.text).join(", ").split(/\s*[,;•|·]\s*/).map(x=>x.replace(/[.]$/,"").trim()).filter(Boolean);
    if(parts.length>=5 && parts.every(p=>p.length<=40)) items=parts;
  }
  if(!items || items.filter(x=>/[.!?]$/.test(x)).length>items.length/3) return null;   // sentences are not tags
  return items;
}
function structureSection(s){
  const title=normText(s.title).trim();
  const lines=fixLoneBullets(normText(s.body).split("\n").map(l=>l.trim()));
  // a first line repeating the section title ("ПРОФЕССИОНАЛЬНЫЙ ПРОФИЛЬ" under "Профиль") is dropped
  const fi=lines.findIndex(Boolean);
  if(fi>=0 && title){
    const a=lines[fi].toLowerCase().replace(/[:\s]+$/,""), b=title.toLowerCase();
    if(a===b || (isCapsSub(lines[fi]) && a.includes(b))) lines.splice(fi,1);
  }
  const blocks=structureLines(lines);
  const items=gridItems(title, blocks);
  if(items){
    const avg=items.reduce((a,x)=>a+x.length,0)/items.length;
    return {title, blocks:[{t:"grid", items, chips: avg<=24 && items.every(x=>x.length<=40)}], box:false};
  }
  const box=SUMM_T.test(title) && blocks.length>0 && blocks.length<=5 && blocks.every(b=>b.t==="p"||b.t==="gap");
  return {title, blocks, box};
}
function layoutResume(d){
  return (d.sections||[]).map(structureSection).filter(s=>s.blocks.length);
}

/* ============================ preview (HTML mirror) ============================ */
function escapeHtml(s){return (s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
const CV_CSS=`
.p-name{font-size:2.15em}
.p-head{color:var(--beige-deep);font-weight:500;font-size:1.08em;margin-top:.35em}
.p-contacts{font-size:.86em}
.p-personal{font-size:.8em}
.p-photo{border-radius:10px}
.p-sec{margin-top:1.7em}
.p-sec h3{font-size:.86em;letter-spacing:.13em;margin:0 0 .75em}
.p-sec h3::before{content:"";width:3px;height:1.15em;border-radius:2px;background:var(--beige);flex:0 0 3px}
.p-sec .body{font-size:.94em;line-height:1.5}
.cv-p{margin:0 0 .35em}
.cv-kv b,.cv-ul b{color:var(--graphite);font-weight:500}
.cv-box{background:#FAF6EF;border-left:3px solid var(--beige);border-radius:0 8px 8px 0;padding:.75em 1em}
.cv-box .cv-p:last-child{margin-bottom:0}
.cv-entry{margin-top:1em}
.cv-entry:first-child{margin-top:0}
.cv-er{display:flex;justify-content:space-between;align-items:baseline;gap:1em}
.cv-et{font-weight:700;color:var(--graphite);font-size:1.05em}
.cv-ed{color:var(--beige-deep);font-weight:500;font-size:.88em;white-space:nowrap}
.cv-es{color:var(--muted);font-size:.93em}
.cv-role{font-weight:500;color:var(--graphite);margin-top:.15em}
.cv-lead{font-weight:500;color:var(--graphite);margin:.6em 0 .15em}
.cv-sub{font-weight:700;color:var(--graphite);font-size:.92em;letter-spacing:.04em;margin:.9em 0 .25em}
.cv-ul{list-style:none;margin:.35em 0 .3em;padding:0}
.cv-ul li{position:relative;padding-left:1.15em;margin:.2em 0}
.cv-ul li::before{content:"";position:absolute;left:.25em;top:.62em;width:.38em;height:.38em;border-radius:50%;background:var(--beige)}
.cv-grid{columns:2;column-gap:1.6em}
.cv-grid li{break-inside:avoid}
.cv-chips{display:flex;flex-wrap:wrap;gap:.45em}
.cv-chips span{background:#F4ECDF;color:var(--graphite);border-radius:999px;padding:.25em .8em;font-size:.92em}
.cv-gap{height:.5em}
@media (max-width:560px){.cv-grid{columns:1}.cv-er{flex-wrap:wrap}}
`;
function ensureCss(){
  if(!global.document || document.getElementById("tlnt-cv-css")) return;
  const st=document.createElement("style"); st.id="tlnt-cv-css"; st.textContent=CV_CSS;
  document.head.appendChild(st);
}
function richHtml(t){
  const kv=kvParts(t);
  return kv ? `<b>${escapeHtml(kv.k)}:</b> ${escapeHtml(kv.v)}` : escapeHtml(t);
}
function blocksHtml(sec){
  let html="", ul=[];
  const flushUl=()=>{ if(ul.length){ html+=`<ul class="cv-ul">${ul.map(t=>`<li>${richHtml(t)}</li>`).join("")}</ul>`; ul=[]; } };
  sec.blocks.forEach(b=>{
    if(b.t!=="li") flushUl();
    if(b.t==="li") ul.push(b.text);
    else if(b.t==="p") html+=`<p class="cv-p">${richHtml(b.text)}</p>`;
    else if(b.t==="kv") html+=`<p class="cv-p cv-kv"><b>${escapeHtml(b.k)}:</b> ${escapeHtml(b.text)}</p>`;
    else if(b.t==="sub") html+=`<div class="cv-sub">${escapeHtml(b.text)}</div>`;
    else if(b.t==="role") html+=`<div class="cv-role">${escapeHtml(b.text)}</div>`;
    else if(b.t==="lead") html+=`<div class="cv-lead">${escapeHtml(b.text)}</div>`;
    else if(b.t==="gap") html+=`<div class="cv-gap"></div>`;
    else if(b.t==="entry"){
      const date=b.date?`<span class="cv-ed">${escapeHtml(b.date)}</span>`:"";
      html+= b.title
        ? `<div class="cv-entry"><div class="cv-er"><span class="cv-et">${escapeHtml(b.title)}</span>${date}</div>${b.sub?`<div class="cv-es">${escapeHtml(b.sub)}</div>`:""}</div>`
        : `<div class="cv-entry"><div class="cv-er"><span class="cv-es">${escapeHtml(b.sub)}</span>${date}</div></div>`;
    }
    else if(b.t==="grid"){
      html+= b.chips
        ? `<div class="cv-chips">${b.items.map(x=>`<span>${escapeHtml(x)}</span>`).join("")}</div>`
        : `<ul class="cv-ul cv-grid">${b.items.map(x=>`<li>${richHtml(x)}</li>`).join("")}</ul>`;
    }
  });
  flushUl();
  return sec.box ? `<div class="cv-box">${html}</div>` : html;
}
function safeImg(v){ return (typeof v==="string" && /^data:image\/(png|jpe?g|webp|gif);base64,[a-z0-9+/=\s]+$/i.test(v)) ? v : ""; }
function footerLeft(d){ return (d&&d.lang==="en")
  ? "Prepared by TLNT.AE - hiring consultancy, Dubai, UAE"
  : "Подготовлено TLNT.AE - консалтинг по подбору и найму, Дубай, ОАЭ"; }
function renderPreview(el, d){
  ensureCss();
  const n=s=>normText(s).trim();
  const contacts=[d.email,d.phone,d.loc,d.link].map(n).filter(Boolean);
  const logo=safeImg(d.logo), photo=safeImg(d.photo);
  const logoHtml = logo ? `<img class="p-logo-img" src="${logo}">` : `<div class="p-logo">TLNT<span class="dot">.</span>AE</div>`;
  const photoHtml = photo ? `<img class="p-photo" src="${photo}">` : "";
  const personal=n(d.personal);
  el.innerHTML=`
    <div class="p-mast">${logoHtml}<div class="p-tag">Hiring Consultancy<br>United Arab Emirates</div></div>
    <div class="p-headrow">
      <div class="p-headmain">
        <div class="p-name">${escapeHtml(n(d.name)||n(d.head)||"Имя Фамилия")}</div>
        ${n(d.name)&&n(d.head)?`<div class="p-head">${escapeHtml(n(d.head))}</div>`:""}
        ${contacts.length?`<div class="p-contacts">${contacts.map(escapeHtml).join('<span>·</span>')}</div>`:""}
        ${personal?`<div class="p-personal">${escapeHtml(personal).replace(/\n+/g,' &nbsp;·&nbsp; ')}</div>`:""}
      </div>
      ${photoHtml?`<div class="p-photowrap">${photoHtml}</div>`:""}
    </div>
    ${layoutResume(d).map(s=>`<div class="p-sec">${s.title?`<h3>${escapeHtml(s.title)}</h3>`:""}<div class="body">${blocksHtml(s)}</div></div>`).join("")}
    <div class="p-foot"><span>${escapeHtml(footerLeft(d))}</span><span>tlnt.ae</span></div>`;
}

/* ============================ PDF build ============================ */
// words of styled runs -> lines that fit maxW; a word wider than the line is cut
function wrapRuns(doc, runs, maxW, size){
  const toks=[];
  runs.forEach(r=>String(r.t||"").split(/( )/).forEach(p=>{ if(p!=="") toks.push({t:p, f:r.f, c:r.c}); }));
  const width=o=>{ doc.setFont("Roboto",o.f); doc.setFontSize(size); return doc.getTextWidth(o.t); };
  const lines=[]; let cur=[], w=0;
  const push=()=>{ while(cur.length && cur[cur.length-1].t===" ") w-=width(cur.pop()); if(cur.length) lines.push(cur); cur=[]; w=0; };
  toks.forEach(o=>{
    if(o.t===" "){ if(cur.length){ cur.push(o); w+=width(o); } return; }
    let ow=width(o);
    if(w+ow>maxW && cur.length) push();
    while(ow>maxW && o.t.length>1){
      let n=o.t.length-1; while(n>1 && width({t:o.t.slice(0,n), f:o.f})>maxW) n--;
      cur.push({t:o.t.slice(0,n), f:o.f, c:o.c}); push();
      o={t:o.t.slice(n), f:o.f, c:o.c}; ow=width(o);
    }
    cur.push(o); w+=ow;
  });
  push();
  return lines;
}
function drawRunLine(doc, line, x, y, size){
  const segs=[];
  line.forEach(o=>{ const s=segs[segs.length-1]; if(s && s.f===o.f && s.c===o.c) s.t+=o.t; else segs.push({t:o.t, f:o.f, c:o.c}); });
  segs.forEach(s=>{ doc.setFont("Roboto",s.f); doc.setFontSize(size); doc.setTextColor(s.c[0],s.c[1],s.c[2]); doc.text(s.t,x,y); x+=doc.getTextWidth(s.t); });
}
async function buildResumeDoc(d, cb){
  const f=await ensureFonts(cb);
  const { jsPDF }=global.jspdf;
  const doc=new jsPDF({unit:"pt",format:"a4"});
  doc.addFileToVFS("R-r.ttf",f.reg);  doc.addFont("R-r.ttf","Roboto","normal");
  doc.addFileToVFS("R-m.ttf",f.med);  doc.addFont("R-m.ttf","Roboto","medium");
  doc.addFileToVFS("R-b.ttf",f.bold); doc.addFont("R-b.ttf","Roboto","bold");

  const W=doc.internal.pageSize.getWidth(), H=doc.internal.pageSize.getHeight();
  const M=48, CW=W-M*2, BOTTOM=H-60;
  const GRAPH=[63,58,51], INK=[74,68,60], MUT=[124,116,104], BEI=[176,141,87], BEID=[154,120,66], LINE=[231,222,207],
        BOX=[250,246,239], CHIP=[244,236,223];
  const BS=10, LH=14.4;                      // body size and line step
  const base=s=>s*1.02;                      // baseline offset inside a line box
  const n=s=>normText(s).trim();
  let y=0, top=0;

  const font=(st,sz,c)=>{ doc.setFont("Roboto",st); doc.setFontSize(sz); doc.setTextColor(c[0],c[1],c[2]); };
  const put=(t,x,yy,st,sz,c,opt)=>{ font(st,sz,c); doc.text(t,x,yy,opt||{}); };
  const tw=(t,st,sz)=>{ doc.setFont("Roboto",st); doc.setFontSize(sz); return doc.getTextWidth(t); };
  const fill=c=>doc.setFillColor(c[0],c[1],c[2]);
  const stroke=(c,w)=>{ doc.setDrawColor(c[0],c[1],c[2]); doc.setLineWidth(w); };
  const runsOf=(t,c)=>{ const kv=kvParts(t); return kv ? [{t:kv.k+": ", f:"medium", c:GRAPH},{t:kv.v, f:"normal", c:c||INK}] : [{t, f:"normal", c:c||INK}]; };
  const dot=(x,yy)=>{ fill(BEI); doc.circle(x, yy-3.3, 1.55, "F"); };

  const runHead=[n(d.name), n(d.head)].filter(Boolean).join("  ·  ");
  function masthead(first){
    const baseY=first?50:38;
    font("bold", first?16:11.5, GRAPH);
    doc.text("TLNT", M, baseY, {charSpace:1.1});
    const t1=doc.getTextWidth("TLNT");
    font("bold", first?16:11.5, BEI); doc.text(".", M+t1+2, baseY); const dw=doc.getTextWidth(".");
    font("bold", first?16:11.5, GRAPH); doc.text("AE", M+t1+dw+3, baseY, {charSpace:1.1});
    if(first) put("HIRING CONSULTANCY · UAE", W-M, baseY-6, "normal", 7.5, BEID, {align:"right", charSpace:1.4});
    else if(runHead){
      let t=runHead; font("normal",8,MUT);
      while(t.length>4 && doc.getTextWidth(t)>CW-110) t=t.slice(0,-2);
      if(t!==runHead) t=t.replace(/\s*\S?$/,"")+"...";
      doc.text(t, W-M, baseY-1, {align:"right"});
    }
    const ly=first?60:47;
    stroke(BEI, first?1.1:.8); doc.line(M,ly,W-M,ly);
    return ly+(first?20:18);
  }
  function newPage(){ doc.addPage(); y=masthead(false); top=y; }
  function need(h){ if(y+h>BOTTOM && y>top+1) newPage(); }

  y=masthead(true);

  // ---- header: name, position, contacts on the left; photo with rounded corners on the right ----
  let photoW=0, photoH=0;
  const photoSafe=safeImg(d.photo);
  if(photoSafe){
    try{
      const pr=doc.getImageProperties(photoSafe);
      photoW=90; photoH=112;
      const px=W-M-photoW, py=y, r=Math.max(photoW/pr.width, photoH/pr.height), iw=pr.width*r, ih=pr.height*r;
      doc.saveGraphicsState();
      doc.roundedRect(px,py,photoW,photoH,8,8,null); doc.clip(); doc.discardPath();
      doc.addImage(photoSafe, pr.fileType||"JPEG", px-(iw-photoW)/2, py-(ih-photoH)*0.25, iw, ih);   // cover, keep the face
      doc.restoreGraphicsState();
      stroke(LINE,.8); doc.roundedRect(px,py,photoW,photoH,8,8,"S");
    }catch(e){ photoW=0; photoH=0; }
  }
  const textW = photoW? CW-photoW-20 : CW;
  let ly=y+2;
  // no name in the source (an anonymous export): the position becomes the big title
  const bigName=n(d.name)||n(d.head), headLine=n(d.name)?n(d.head):"";
  if(bigName) wrapRuns(doc,[{t:bigName, f:"bold", c:GRAPH}], textW, 22).forEach(l=>{ drawRunLine(doc,l,M,ly+19,22); ly+=26; });
  if(headLine){
    ly+=1;
    wrapRuns(doc,[{t:headLine, f:"medium", c:BEID}], textW, 11.5).forEach(l=>{ drawRunLine(doc,l,M,ly+11,11.5); ly+=15.5; });
  }
  const contacts=[d.email,d.phone,d.loc,d.link].map(n).filter(Boolean);
  if(contacts.length){
    ly+=6; let x=M; const cs=9.2;
    contacts.forEach((c,idx)=>{
      const w=tw(c,"normal",cs);
      if(x>M && x+w>M+textW){ ly+=13; x=M; }
      put(c,x,ly+9,"normal",cs,INK); x+=w;
      if(idx<contacts.length-1){ put("  ·  ",x,ly+9,"bold",cs,BEI); x+=tw("  ·  ","bold",cs); }
    });
    ly+=14;
  }
  if(d.personal){
    ly+=3;
    wrapRuns(doc,[{t:n(d.personal).replace(/\n+/g,"  ·  "), f:"normal", c:MUT}], textW, 8.8).forEach(l=>{ drawRunLine(doc,l,M,ly+9,8.8); ly+=12; });
  }
  y=Math.max(ly, y+photoH)+14;
  stroke(LINE,.8); doc.line(M,y,W-M,y); y+=20; top=y;

  // ---- sections ----
  function sectionTitle(t){
    need(24+LH*3);
    if(y>top) y+=6;
    fill(BEI); doc.rect(M, y+1, 2.8, 11, "F");
    const T=t.toUpperCase();
    put(T, M+10, y+10.6, "bold", 10, BEID, {charSpace:1.15});
    const x2=M+10+tw(T,"bold",10)+T.length*1.15+10;
    if(x2<W-M){ stroke(LINE,.6); doc.line(x2, y+6.6, W-M, y+6.6); }
    y+=24;
  }
  function textLines(lines, x, size, lh){
    lines.forEach(l=>{ need(lh); drawRunLine(doc,l,x,y+base(size),size); y+=lh; });
  }
  function drawBlock(b, prev){
    if(b.t==="gap"){ y+=5; return; }
    if(b.t==="p"){ textLines(wrapRuns(doc,runsOf(b.text),CW,BS), M, BS, LH); y+=3; return; }
    if(b.t==="kv"){ textLines(wrapRuns(doc,[{t:b.k+": ",f:"medium",c:GRAPH},{t:b.text,f:"normal",c:INK}],CW,BS), M, BS, LH); y+=3; return; }
    if(b.t==="li"){
      const ls=wrapRuns(doc,runsOf(b.text),CW-14,BS);
      need(Math.min(ls.length,2)*LH);
      ls.forEach((l,j)=>{ need(LH); if(j===0) dot(M+4.5, y+base(BS)); drawRunLine(doc,l,M+14,y+base(BS),BS); y+=LH; });
      y+=2; return;
    }
    if(b.t==="sub"){ need(LH*2.6); y+= prev? 6 : 0; put(b.text, M, y+base(9.6), "bold", 9.6, GRAPH, {charSpace:.5}); y+=LH+2; return; }
    if(b.t==="role"){ textLines(wrapRuns(doc,[{t:b.text,f:"medium",c:GRAPH}],CW,BS), M, BS, LH); y+=2; return; }
    if(b.t==="lead"){ need(LH*2); y+= prev && prev.t!=="gap" ? 4 : 0; textLines(wrapRuns(doc,[{t:b.text,f:"medium",c:GRAPH}],CW,BS), M, BS, LH); y+=1; return; }
    if(b.t==="entry"){
      const TS=10.8, DS=9;
      const dW=b.date? tw(b.date,"medium",DS)+16 : 0;
      const tl=b.title? wrapRuns(doc,[{t:b.title,f:"bold",c:GRAPH}], CW-dW, TS) : [];
      const sl=b.sub? wrapRuns(doc,[{t:b.sub,f:"normal",c:MUT}], b.title? CW : CW-dW, 9.6) : [];
      y+= !prev ? 0 : prev.t==="gap" ? 4 : 10;
      need(Math.max(tl.length,1)*15 + (b.title? sl.length*13 : 0) + LH*2);
      if(tl.length){
        tl.forEach((l,j)=>{ drawRunLine(doc,l,M,y+base(TS),TS); if(j===0 && b.date) put(b.date, W-M, y+base(TS), "medium", DS, BEID, {align:"right"}); y+=15; });
        sl.forEach(l=>{ drawRunLine(doc,l,M,y+base(9.6),9.6); y+=13; });
      } else {
        if(sl.length) drawRunLine(doc,sl[0],M,y+base(9.6),9.6);
        if(b.date) put(b.date, W-M, y+base(9.6), "medium", DS, BEID, {align:"right"});
        y+=14;
        sl.slice(1).forEach(l=>{ drawRunLine(doc,l,M,y+base(9.6),9.6); y+=13; });
      }
      y+=3; return;
    }
    if(b.t==="grid"){
      if(b.chips){
        const cs=9.4, ch=18, pad=9, gap=6; let x=M;
        need(ch+4);
        b.items.forEach(it=>{
          const w=Math.min(tw(it,"normal",cs)+pad*2, CW);
          if(x>M && x+w>W-M+0.1){ x=M; y+=ch+gap; need(ch+2); }
          fill(CHIP); doc.roundedRect(x,y,w,ch,ch/2,ch/2,"F");
          put(it, x+pad, y+ch/2+cs*0.35, "normal", cs, GRAPH);
          x+=w+gap;
        });
        y+=ch+6; return;
      }
      const gap=22, colW=(CW-gap)/2;
      // two independent columns (read down the left one, then the right one), split where their heights are closest
      const wr=b.items.map(t=>wrapRuns(doc,runsOf(t),colW-14,BS));
      const hs=wr.map(ls=>ls.length*LH+2), total=hs.reduce((a,h)=>a+h,0);
      let k=0, acc=0, best=Infinity;
      for(let j=0;j<=wr.length;j++){ const d2=Math.abs(total-2*acc); if(d2<best){ best=d2; k=j; } if(j<wr.length) acc+=hs[j]; }
      const colH=Math.max(hs.slice(0,k).reduce((a,h)=>a+h,0), hs.slice(k).reduce((a,h)=>a+h,0));
      if(colH<=BOTTOM-top-10){
        need(colH);
        [[0,k],[k,wr.length]].forEach(([a,z],ci)=>{
          const x=M+ci*(colW+gap); let yy=y;
          for(let j=a;j<z;j++){ dot(x+4.5, yy+base(BS)); wr[j].forEach((l,li)=>drawRunLine(doc,l,x+14,yy+base(BS)+li*LH,BS)); yy+=hs[j]; }
        });
        y+=colH; return;
      }
      for(let i=0;i<b.items.length;i+=2){      // taller than a page: rows that can break across pages
        const cols=[b.items[i], b.items[i+1]].map(t=> t==null ? [] : wrapRuns(doc,runsOf(t),colW-14,BS));
        const rows=Math.max(cols[0].length, cols[1].length);
        need(rows*LH);
        cols.forEach((ls,ci)=>{ if(!ls.length) return; const x=M+ci*(colW+gap);
          dot(x+4.5, y+base(BS)); ls.forEach((l,j)=>drawRunLine(doc,l,x+14,y+base(BS)+j*LH,BS)); });
        y+=rows*LH+2;
      }
      return;
    }
  }
  function drawBox(sec){
    // summary / profile: light panel with a gold rule; falls back to plain text when it does not fit one page
    const parts=sec.blocks.filter(b=>b.t==="p").map(b=>wrapRuns(doc,runsOf(b.text),CW-28,BS));
    const h=parts.reduce((a,ls)=>a+ls.length*LH,0)+(parts.length-1)*5+16;
    if(h>BOTTOM-top-10){ sec.blocks.forEach((b,i)=>drawBlock(b, sec.blocks[i-1])); return; }
    need(h);
    fill(BOX); doc.roundedRect(M,y,CW,h,5,5,"F");
    fill(BEI); doc.rect(M,y,2.8,h,"F");
    let yy=y+8;
    parts.forEach((ls,pi)=>{ if(pi) yy+=5; ls.forEach(l=>{ drawRunLine(doc,l,M+16,yy+base(BS),BS); yy+=LH; }); });
    y+=h+4;
  }

  layoutResume(d).forEach(sec=>{
    if(sec.title) sectionTitle(sec.title);
    if(sec.box) drawBox(sec);
    else sec.blocks.forEach((b,i)=>drawBlock(b, sec.blocks[i-1]));
    y+=10;
  });

  // ---- footer on every page: agency line + page number ----
  const pages=doc.getNumberOfPages();
  for(let p=1;p<=pages;p++){
    doc.setPage(p);
    stroke(LINE,.6); doc.line(M,H-42,W-M,H-42);
    put(footerLeft(d), M, H-29, "normal", 7.6, MUT);
    put(pages>1 ? `tlnt.ae  ·  ${p} / ${pages}` : "tlnt.ae", W-M, H-29, "normal", 7.6, MUT, {align:"right"});
  }
  return doc;
}
function uniqueStamp(){
  const d=new Date(), p=n=>String(n).padStart(2,"0");
  const rnd=Math.floor(Math.random()*1296).toString(36).padStart(2,"0"); // avoid same-second clashes
  return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}_${rnd}`;
}
async function downloadResumePdf(d, cb){
  const doc=await buildResumeDoc(d, cb);
  const base=(d.name||d.head||"resume").replace(/[^\wЀ-ӿ\- ]/g,"").trim().replace(/\s+/g,"_").slice(0,40)||"resume";
  doc.save(`TLNT_${base}_${uniqueStamp()}.pdf`);
}

/* ============================ share payload ============================ */
function encodePayload(d){
  const json=JSON.stringify(d);
  return global.LZString.compressToEncodedURIComponent(json);
}
function decodePayload(str){
  try{ const json=global.LZString.decompressFromEncodedURIComponent(str); return json?JSON.parse(json):null; }
  catch(e){ return null; }
}

global.TLNT = {
  ensureFonts, extractFile, extractPdf, reconstructLines, joinRowItems, collapseTracked, cleanText, parseResume, isHeader, findPhone,
  renderPreview, buildResumeDoc, downloadResumePdf, layoutResume, normText, reflowText, BULLET_CHARS, textChars, isWatermarkLine,
  encodePayload, decodePayload, imgToDataUrl
};
})(window);
